hosts:
  - wpapi.local

site:
  name: WP-API Testbed

extensions:
  - kadamwhite/chassis-wxr

plugins:
  - https://github.com/WP-API/Basic-Auth/archive/master.zip

wxr:
  path: theme-unit-test-data.xml
  clean: true
